spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/allforone
    username: root
    password: root

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.yl.wallet.mapper

logging:
  level:
    com.yl.wallet.mapper: DEBUG
